services:
    app:
        image: node:18-alpine
        command: sh -c "npm install && npm run dev"
        ports:
            - 3000:3000
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: produce
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0
        volumes:
            - produce-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: produce
volumes:
    produce-mysql-data:
